version: "3.9"

services:
  database:
    image: mongo:5
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}

  foodbackend:
    image: tacar/food_app_backend:latest
    ports: [ "3000:3000" ]
    environment:
      NODE_ENV: ${NODE_ENV}
      EXPRESS_PORT: ${EXPRESS_PORT}
      MONGO_URI: ${MONGO_URI}
      AUTH_TOKEN_SEC: ${AUTH_TOKEN_SEC}
    depends_on:
      - database


