version: "3.9"

services:
  database:
    image: mongo:5
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${mongo_user}
      MONGO_INITDB_ROOT_PASSWORD: ${mongo_pass}
      MONGO_INITDB_DATABASE: ${mongo_database}

  foodbackend:
    image: tacar/food_app_backend:2
    ports: [ "3000:3000" ]
    environment:
      NODE_ENV: ${node_env}
      EXPRESS_PORT: ${express_port}
      MONGO_INITDB_ROOT_USERNAME: ${mongo_user}
      MONGO_INITDB_ROOT_PASSWORD: ${mongo_pass}
      MONGO_DATABASE: ${mongo_database}
      MONGO_URL: ${mongo_url}
    depends_on:
      - database


